---
- name: Ansible Ping play
  hosts: all
  tasks:
    - name: Ping
      ansible.builtin.ping:
      register: ping_results
    - name: Print Ping Results
      ansible.builtin.debug:
        var: ping_results
